spring.application.name=ToHoClicker

spring.datasource.url = jdbc:postgresql://localhost:5432/tohodb
spring.datasource.username = postgres
spring.datasource.password = SuperUserPostgre

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update